services:
  web:
    image: osticket-docker:v1.18.1
    container_name: webapp
    hostname: osticket
    restart: always
    ports:
      - 80:80
    environment:
      - OSTICKET_DB_HOST=db
      - OSTICKET_DB_USER=osticket
      - OSTICKET_DB_PASSWORD=osticketpass
      - OSTICKET_DB_NAME=osticket
  db:
    image: mysql:lts
    container_name: db
    hostname: mysql-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpass
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=osticketpass
    expose:
      - 3306

volumes:
  db_data:
