services:
  osticket:
    image: osticket-docker:apache
    container_name: webapp
    hostname: osticket-container
    volumes:
      - ./app:/var/www/html
    restart: unless-stopped
    ports:
      - 80:80
  db:
    image: mysql:lts
    container_name: db
    hostname: mysql-db
    volumes:
      - ./osticket_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
    ports:
      - "3306:3306"

