services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: osticket:v1.18.1
    container_name: web
    hostname: osticket
    restart: always
    ports:
      - 80:80
    environment:
      - OSTICKET_DB_HOST=db
      - OSTICKET_DB_USER=osticket
      - OSTICKET_DB_PASSWORD=osticketpass
      - OSTICKET_DB_NAME=osticket
  db:
    image: mysql:8.0.27
    container_name: db
    hostname: mysql-db
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpass
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=osticketpass
    expose:
      - 3306

volumes:
  db_data:
