FROM php:8.2.19-apache

COPY app/ /var/www/html/osticket/

# Set proper ownership for root directory and files
RUN chown -R www-data:www-data /var/www/html \
    && chmod 2775 /var/www/html && find /var/www/html -type d -exec chmod 2775 {} \; \
    && find /var/www/html -type f -exec chmod 0664 {} \;